<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-9FQ5FG2" name="com.qa.SalesForce.Test.HomePageTest" tests="5" failures="1" timestamp="05 Jul 2020 12:15:34 GMT" time="147.869" errors="0">
  <testcase name="varifyHomePageTitleTest" time="23.354" classname="com.qa.SalesForce.Test.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [LinkedIn] but found [(17) LinkedIn]">
      <![CDATA[java.lang.AssertionError: expected [LinkedIn] but found [(17) LinkedIn]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.qa.SalesForce.Test.HomePageTest.varifyHomePageTitleTest(HomePageTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.qa.SalesForce.Test.RunnerClass.main(RunnerClass.java:14)
]]>
    </failure>
  </testcase> <!-- varifyHomePageTitleTest -->
  <testcase name="ClickMyNetworkPageTest" time="30.331" classname="com.qa.SalesForce.Test.HomePageTest"/>
  <testcase name="ClickOnJobPageTest" time="33.951" classname="com.qa.SalesForce.Test.HomePageTest"/>
  <testcase name="ClickOnMessgaingPageTest" time="28.144" classname="com.qa.SalesForce.Test.HomePageTest"/>
  <testcase name="ClickOnNotificationPageTest" time="32.089" classname="com.qa.SalesForce.Test.HomePageTest"/>
</testsuite> <!-- com.qa.SalesForce.Test.HomePageTest -->
